### ISSUE TITLE
36: [[: not found &  41: [[: not found

### ISSUE THREAD

**Issue by michaelgiraldo** [gavinfielder/pft#16]
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes: 39 bits physical, 48 bits virtual
Linux version: 5.4.43-04832-g7fb2244e3c65 

**mg@penguin:~/42_cadet/ft_printf/pft$ ./enable-test**
./enable-test: 24: [: unexpected operator
Enabling tests...
./src/select_numeric.php: enabled 1973 tests from 0 to 2616
make: Entering directory '/home/mg/42_cadet/ft_printf/pft'
make[1]: Entering directory '/home/mg/42_cadet/ft_printf/pft'
make[1]: Leaving directory '/home/mg/42_cadet/ft_printf/pft'
make: Leaving directory '/home/mg/42_cadet/ft_printf/pft'
Done.
./enable-test: 36: [[: not found
./enable-test: 41: [[: not found
**mg@penguin:~/42_cadet/ft_printf/pft$ ./disable-test n**
./disable-test: 24: [: n: unexpected operator
Disabling tests...
./src/select_query.php: disabled 219 tests with names matching "n.*"
make: Entering directory '/home/mg/42_cadet/ft_printf/pft'
make[1]: Entering directory '/home/mg/42_cadet/ft_printf/pft'
make[1]: Leaving directory '/home/mg/42_cadet/ft_printf/pft'
make: Leaving directory '/home/mg/42_cadet/ft_printf/pft'
Done.
./disable-test: 36: [[: not found
./disable-test: 41: [[: not found

**Comment by gavinfielder** [comment]
Thanks for the report @michaelgiraldo 

This seems like a bash incompatibility, if you indeed your system is running the script with bash.

Could you change the top to `#!/bin/bash` and see if you get the same result?

**Comment by michaelgiraldo** [comment]
However it does not work for.
**$ /bin/bash ./reset-to-default-enabled-tests** 
./enable-test: 24: [: -q: unexpected operator
./enable-test: 29: [: 1: unexpected operator
Enabling tests...
./src/select_numeric.php: enabled 0 tests from 0 to 4218
make: Entering directory '/home/mg/42_cadet/ft_printf/mg_pft'
make[1]: Entering directory '/home/mg/42_cadet/ft_printf/mg_pft'
make[1]: Leaving directory '/home/mg/42_cadet/ft_printf/mg_pft'
make: Leaving directory '/home/mg/42_cadet/ft_printf/mg_pft'
Done.
./enable-test: 44: [[: not found
./enable-test: 49: [[: not found
./disable-test: 24: [: -q: unexpected operator
./disable-test: 29: bonus: not found
Disabling tests...

**Comment by gavinfielder** [comment]
The problem is that your system doesn't use bash as its default and the reset script just invokes the other two as an executable. I've changed the scripts to use bash explicitly, so it should work now.
